// app/layout.tsx hoặc app/RootLayout.tsx tùy cấu trúc dự án của bạn
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactLenis } from "@/utils/lenis";
import MarqueeBg from "./(decor)/MarqueeBg";
import Header from "@/components/Header/header";
import LoadingOverlay from "@/components/Loading/LoadingOverlay";
import { LoadingProvider } from "@/providers/LoadingProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis
        root
        options={{
          duration: 1.8, // Tăng giá trị này để làm chậm cuộn (mặc định thường là 1.2)
        }}
      >
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <LoadingProvider>
            <LoadingOverlay />
            <Header />
            <MarqueeBg />
            {children}
          </LoadingProvider>
        </body>
      </ReactLenis>
    </html>
  );
}
